import { text, integer, timestamp, index, uniqueIndex, jsonb } from "drizzle-orm/pg-core";
import { labelSuiteSchema as schema } from "./_shared";
import { orgs } from "./foundation";
import { artists, releases, tracks } from "./catalog";

// ─── Analytics Imports ─────────────────────────────────
export const analytics_import_runs = schema.table("analytics_import_runs", {
  id: text("id").primaryKey(),
  org_id: text("org_id").notNull().default("true-nature").references(() => orgs.id),
  source: text("source").notNull(),
  artist_id: text("artist_id").references(() => artists.id),
  release_id: text("release_id").references(() => releases.id),
  track_id: text("track_id").references(() => tracks.id),
  mode: text("mode").notNull().default("sync"),
  requested_date_range: text("requested_date_range"),
  requested_aggregation: text("requested_aggregation"),
  status: text("status").notNull().default("running"),
  started_at: timestamp("started_at").defaultNow(),
  completed_at: timestamp("completed_at"),
  files_downloaded: integer("files_downloaded").default(0),
  rows_imported: integer("rows_imported").default(0),
  rows_inserted: integer("rows_inserted").default(0),
  rows_updated: integer("rows_updated").default(0),
  rows_unchanged: integer("rows_unchanged").default(0),
  error: text("error"),
  metadata: jsonb("metadata").$type<Record<string, unknown>>(),
}, (table) => [
  index("analytics_import_runs_org_id_idx").on(table.org_id),
  index("analytics_import_runs_artist_id_idx").on(table.org_id, table.artist_id),
  index("analytics_import_runs_release_id_idx").on(table.org_id, table.release_id),
  index("analytics_import_runs_track_id_idx").on(table.org_id, table.track_id),
  index("analytics_import_runs_source_status_idx").on(table.source, table.status),
  index("analytics_import_runs_started_at_idx").on(table.started_at),
]);

export const analytics_import_files = schema.table("analytics_import_files", {
  id: text("id").primaryKey(),
  org_id: text("org_id").notNull().default("true-nature").references(() => orgs.id),
  run_id: text("run_id").notNull().references(() => analytics_import_runs.id),
  source: text("source").notNull(),
  dashboard_url: text("dashboard_url"),
  widget_key: text("widget_key").notNull(),
  widget_title: text("widget_title"),
  artist_id: text("artist_id").references(() => artists.id),
  release_id: text("release_id").references(() => releases.id),
  track_id: text("track_id").references(() => tracks.id),
  requested_date_range: text("requested_date_range"),
  requested_aggregation: text("requested_aggregation"),
  file_name: text("file_name").notNull(),
  local_path: text("local_path"),
  storage_bucket: text("storage_bucket"),
  storage_key: text("storage_key"),
  storage_status: text("storage_status").notNull().default("not_requested"),
  storage_uploaded_at: timestamp("storage_uploaded_at", { withTimezone: true }),
  storage_error: text("storage_error"),
  sha256: text("sha256").notNull(),
  byte_size: integer("byte_size").notNull(),
  row_count: integer("row_count").default(0),
  headers: jsonb("headers").$type<string[]>(),
  created_at: timestamp("created_at").defaultNow(),
}, (table) => [
  index("analytics_import_files_org_id_idx").on(table.org_id),
  index("analytics_import_files_run_id_idx").on(table.run_id),
  index("analytics_import_files_artist_id_idx").on(table.org_id, table.artist_id),
  index("analytics_import_files_release_id_idx").on(table.org_id, table.release_id),
  index("analytics_import_files_track_id_idx").on(table.org_id, table.track_id),
  index("analytics_import_files_widget_idx").on(table.org_id, table.source, table.widget_key),
  index("analytics_import_files_content_idx").on(table.org_id, table.source, table.widget_key, table.sha256),
]);

export const analytics_metric_rows = schema.table("analytics_metric_rows", {
  id: text("id").primaryKey(),
  org_id: text("org_id").notNull().default("true-nature").references(() => orgs.id),
  source: text("source").notNull(),
  widget_key: text("widget_key").notNull(),
  artist_id: text("artist_id").references(() => artists.id),
  release_id: text("release_id").references(() => releases.id),
  track_id: text("track_id").references(() => tracks.id),
  row_key: text("row_key").notNull(),
  row_hash: text("row_hash").notNull(),
  requested_date_range: text("requested_date_range").notNull(),
  requested_aggregation: text("requested_aggregation").notNull(),
  dimensions: jsonb("dimensions").$type<Record<string, string | null>>().notNull(),
  metrics: jsonb("metrics").$type<Record<string, number | null>>().notNull(),
  raw_row: jsonb("raw_row").$type<Record<string, string | null>>().notNull(),
  first_seen_run_id: text("first_seen_run_id").references(() => analytics_import_runs.id),
  last_seen_run_id: text("last_seen_run_id").references(() => analytics_import_runs.id),
  first_seen_at: timestamp("first_seen_at").defaultNow(),
  last_seen_at: timestamp("last_seen_at").defaultNow(),
}, (table) => [
  index("analytics_metric_rows_org_id_idx").on(table.org_id),
  index("analytics_metric_rows_artist_id_idx").on(table.org_id, table.artist_id),
  index("analytics_metric_rows_release_id_idx").on(table.org_id, table.release_id),
  index("analytics_metric_rows_track_id_idx").on(table.org_id, table.track_id),
  index("analytics_metric_rows_widget_idx").on(table.org_id, table.source, table.widget_key),
  index("analytics_metric_rows_range_idx").on(table.org_id, table.source, table.widget_key, table.requested_aggregation, table.requested_date_range),
  index("analytics_metric_rows_membership_idx").on(
    table.org_id,
    table.source,
    table.widget_key,
    table.artist_id,
    table.last_seen_run_id,
  ),
  uniqueIndex("analytics_metric_rows_key_unique_idx").on(
    table.org_id,
    table.source,
    table.widget_key,
    table.requested_aggregation,
    table.requested_date_range,
    table.row_key,
  ),
]);

export const analytics_metric_changes = schema.table("analytics_metric_changes", {
  id: text("id").primaryKey(),
  org_id: text("org_id").notNull().default("true-nature").references(() => orgs.id),
  run_id: text("run_id").notNull().references(() => analytics_import_runs.id),
  metric_row_id: text("metric_row_id").notNull().references(() => analytics_metric_rows.id),
  source: text("source").notNull(),
  widget_key: text("widget_key").notNull(),
  artist_id: text("artist_id").references(() => artists.id),
  release_id: text("release_id").references(() => releases.id),
  track_id: text("track_id").references(() => tracks.id),
  row_key: text("row_key").notNull(),
  change_type: text("change_type").notNull(),
  previous_hash: text("previous_hash"),
  current_hash: text("current_hash"),
  previous_raw_row: jsonb("previous_raw_row").$type<Record<string, string | null>>(),
  current_raw_row: jsonb("current_raw_row").$type<Record<string, string | null>>(),
  changed_at: timestamp("changed_at").defaultNow(),
}, (table) => [
  index("analytics_metric_changes_org_id_idx").on(table.org_id),
  index("analytics_metric_changes_run_id_idx").on(table.run_id),
  index("analytics_metric_changes_metric_row_id_idx").on(table.metric_row_id),
  index("analytics_metric_changes_artist_id_idx").on(table.org_id, table.artist_id),
  index("analytics_metric_changes_release_id_idx").on(table.org_id, table.release_id),
  index("analytics_metric_changes_track_id_idx").on(table.org_id, table.track_id),
  index("analytics_metric_changes_widget_idx").on(table.org_id, table.source, table.widget_key),
]);

// Imported evidence remains immutable; this records the human disposition separately.
export const analytics_duplicate_reviews = schema.table("analytics_duplicate_reviews", {
  id: text("id").primaryKey(),
  org_id: text("org_id").notNull().references(() => orgs.id),
  candidate_key: text("candidate_key").notNull(),
  disposition: text("disposition").notNull(),
  reason: text("reason"),
  reviewed_by: text("reviewed_by").notNull(),
  reviewed_at: timestamp("reviewed_at", { withTimezone: true }).notNull(),
}, (table) => [
  uniqueIndex("analytics_duplicate_reviews_org_candidate_unique").on(table.org_id, table.candidate_key),
  index("analytics_duplicate_reviews_org_reviewed_at_idx").on(table.org_id, table.reviewed_at),
]);
