import Foundation
import SwiftUI

public enum NativeJSONValue: Codable, Equatable, Sendable {
  case object([String: NativeJSONValue]), array([NativeJSONValue]), string(String), number(Double), bool(Bool), null
  public init(from decoder: Decoder) throws {
    let c = try decoder.singleValueContainer()
    if c.decodeNil() { self = .null }
    else if let value = try? c.decode(Bool.self) { self = .bool(value) }
    else if let value = try? c.decode(Double.self) { self = .number(value) }
    else if let value = try? c.decode(String.self) { self = .string(value) }
    else if let value = try? c.decode([String: NativeJSONValue].self) { self = .object(value) }
    else { self = .array(try c.decode([NativeJSONValue].self)) }
  }
  public func encode(to encoder: Encoder) throws { var c = encoder.singleValueContainer(); switch self { case let .object(v): try c.encode(v); case let .array(v): try c.encode(v); case let .string(v): try c.encode(v); case let .number(v): try c.encode(v); case let .bool(v): try c.encode(v); case .null: try c.encodeNil() } }
}

public struct NativeCampaignSections: Codable, Equatable, Sendable {
  public let campaign: Campaign; public let content: Content; public let audience: Audience; public let channels: Channels; public let boundaries: Boundaries
  public struct Campaign: Codable, Equatable, Sendable { public let id: String; public let name: String; public let revision: Int; public let updatedAt: String?; enum CodingKeys: String, CodingKey { case id, name, revision, updatedAt = "updated_at" } }
  public struct Content: Codable, Equatable, Sendable { public let selection: TemplateSelection?; public let templateOptions: Bounded<Template>; public let richContent: RichContent; enum CodingKeys: String, CodingKey { case selection, templateOptions = "template_options", richContent = "rich_content" } }
  public struct TemplateSelection: Codable, Equatable, Sendable { public let reviewedTemplateID: String?; public let channel: String?; public let provider: String?; public let sourceVersion: Int?; public let sourceReferences: NativeJSONValue?; public let template: Template?; enum CodingKeys: String, CodingKey { case reviewedTemplateID = "reviewed_template_id", channel, provider, sourceVersion = "source_version", sourceReferences = "source_references", template } }
  public struct Template: Codable, Equatable, Identifiable, Sendable { public let id: String; public let name: String; public let subject: String?; public let channel: String?; public let currentVersion: Int?; public let reviewStatus: String?; public let sourceVersion: Int?; enum CodingKeys: String, CodingKey { case id, name, subject, channel, currentVersion = "current_version", reviewStatus = "review_status", sourceVersion = "source_version" } }
  public struct RichContent: Codable, Equatable, Sendable { public let readOnly: Bool; public let goalDocument: RichDocument; public let notesDocument: RichDocument; public let briefDocument: RichDocument; enum CodingKeys: String, CodingKey { case readOnly = "read_only", goalDocument = "goal_document", notesDocument = "notes_document", briefDocument = "brief_document" } }
  public struct RichDocument: Codable, Equatable, Sendable { public let available: Bool; public let readOnly: Bool; public let document: NativeJSONValue?; public let reason: String?; enum CodingKeys: String, CodingKey { case available, readOnly = "read_only", document, reason } }
  public struct Audience: Codable, Equatable, Sendable { public let selection: AudienceSelection?; public let options: Bounded<AudienceOption> }
  public struct AudienceSelection: Codable, Equatable, Sendable { public let campaignAudienceID: String; public let audienceID: String; public let name: String; public let description: String?; public let counts: Counts; public let includedContacts: Bounded<Member>; public let excludedContacts: Bounded<Member>; public let includedStations: Bounded<Member>; public let excludedStations: Bounded<Member>; enum CodingKeys: String, CodingKey { case campaignAudienceID = "campaign_audience_id", audienceID = "audience_id", name, description, counts, includedContacts = "included_contacts", excludedContacts = "excluded_contacts", includedStations = "included_stations", excludedStations = "excluded_stations" } }
  public struct Counts: Codable, Equatable, Sendable { public let available: Bool; public let reason: String?; public let values: Values?; public struct Values: Codable, Equatable, Sendable { public let includedContacts: Int?; public let excludedContacts: Int?; public let includedStations: Int?; public let excludedStations: Int?; enum CodingKeys: String, CodingKey { case includedContacts = "included_contacts", excludedContacts = "excluded_contacts", includedStations = "included_stations", excludedStations = "excluded_stations" } } }
  public struct AudienceOption: Codable, Equatable, Identifiable, Sendable { public let id: String; public let name: String; public let description: String?; public let membershipRules: NativeJSONValue?; public let updatedAt: String?; enum CodingKeys: String, CodingKey { case id, name, description, membershipRules = "membership_rules", updatedAt = "updated_at" } }
  public struct Member: Codable, Equatable, Identifiable, Sendable { public let id: String; public let name: String? }
  public struct Bounded<Item: Codable & Equatable & Sendable>: Codable, Equatable, Sendable { public let items: [Item]; public let truncated: Bool }
  public struct Channels: Codable, Equatable, Sendable { public let available: Bool; public let reason: String?; public let message: String? }
  public struct Boundaries: Codable, Equatable, Sendable { public let canSend: Bool; public let sendPerformed: Bool; public let editable: [String]; enum CodingKeys: String, CodingKey { case canSend = "can_send", sendPerformed = "send_performed", editable } }
}

public enum NativeCampaignSectionsCommand: Encodable, Equatable, Sendable {
  case selectTemplate(templateID: String?, expectedRevision: Int), attachAudience(audienceID: String, expectedRevision: Int), detachAudience(expectedRevision: Int)
  enum CodingKeys: String, CodingKey { case action, templateID = "template_id", audienceID = "audience_id", expectedRevision = "expected_revision" }
  public func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); switch self { case let .selectTemplate(id, revision): try c.encode("select_template", forKey: .action); try c.encode(id, forKey: .templateID); try c.encode(revision, forKey: .expectedRevision); case let .attachAudience(id, revision): try c.encode("attach_audience", forKey: .action); try c.encode(id, forKey: .audienceID); try c.encode(revision, forKey: .expectedRevision); case let .detachAudience(revision): try c.encode("detach_audience", forKey: .action); try c.encode(revision, forKey: .expectedRevision) } }
  public var consequence: String { switch self { case .selectTemplate: "This changes the reviewed template selection only."; case .attachAudience, .detachAudience: "This changes the campaign audience selection only." } }
}
public struct NativeCampaignSectionsMutationResult: Codable, Equatable, Sendable { public let campaign: Campaign; public let action: String; public let consequences: Consequences; public struct Campaign: Codable, Equatable, Sendable { public let id: String; public let revision: Int }; public struct Consequences: Codable, Equatable, Sendable { public let scope: String; public let canSend: Bool; public let sendPerformed: Bool; public let channelChanges: String; public let recipientDeliveryChanges: String; enum CodingKeys: String, CodingKey { case scope, canSend = "can_send", sendPerformed = "send_performed", channelChanges = "channel_changes", recipientDeliveryChanges = "recipient_delivery_changes" } } }

public struct NativeCampaignSectionsGate: Equatable, Sendable { public let capabilities: [String: Bool]; public private(set) var requiresRefresh = false; public init(capabilities: [String: Bool]) { self.capabilities = capabilities }; public var canMutate: Bool { capabilities["operations.mutate"] == true && !requiresRefresh }; public mutating func requireRefresh() { requiresRefresh = true }; public mutating func markRefreshed() { requiresRefresh = false } }
public struct NativeCampaignSectionsPendingConfirmation: Equatable, Sendable { public let command: NativeCampaignSectionsCommand }
@MainActor public final class NativeCampaignSectionsCoordinator: ObservableObject {
  @Published public private(set) var sections: NativeCampaignSections?; @Published public private(set) var loading = false; @Published public private(set) var mutationInFlight = false; @Published public private(set) var errorMessage: String?; @Published public private(set) var pendingConfirmation: NativeCampaignSectionsPendingConfirmation?; @Published public private(set) var latestRevision: Int?; @Published public private(set) var gate: NativeCampaignSectionsGate
  private var generation = UUID(); private var executing: NativeCampaignSectionsCommand?
  public init(capabilities: [String: Bool]) { gate = .init(capabilities: capabilities) }
  public var requiresRefresh: Bool { gate.requiresRefresh }; public var executingCommand: NativeCampaignSectionsCommand? { executing }
  public func beginLoad() -> UUID { if mutationInFlight { mutationInFlight = false; executing = nil; gate.requireRefresh() }; generation = UUID(); loading = true; return generation }
  public func receiveLoad(_ result: Result<NativeCampaignSections, Error>, token: UUID) { guard token == generation else { return }; loading = false; switch result { case let .success(value): sections = value; latestRevision = value.campaign.revision; gate.markRefreshed(); errorMessage = nil; case let .failure(error): present(error, mutation: false) } }
  public func requestConfirmation(_ command: NativeCampaignSectionsCommand) { guard gate.canMutate, !mutationInFlight else { return }; pendingConfirmation = .init(command: command) }
  public func cancelConfirmation() { pendingConfirmation = nil }
  public func beginConfirmation() -> UUID? { guard gate.canMutate, !mutationInFlight, let pendingConfirmation else { return nil }; executing = pendingConfirmation.command; self.pendingConfirmation = nil; generation = UUID(); loading = false; mutationInFlight = true; return generation }
  public func receiveMutation(_ result: Result<NativeCampaignSectionsMutationResult, Error>, token: UUID) { guard token == generation else { return }; mutationInFlight = false; executing = nil; switch result { case let .success(value): latestRevision = value.campaign.revision; errorMessage = "Confirmed: \(value.consequences.scope). No send, provider, channel, or delivery action occurred. Refresh to view canonical sections."; gate.requireRefresh(); case let .failure(error): gate.requireRefresh(); present(error, mutation: true) } }
  public func load(using operation: @escaping () async throws -> NativeCampaignSections, acceptingResponse: @escaping () -> Bool = { true }) async { let token = beginLoad(); do { let value = try await operation(); guard acceptingResponse() else { invalidate() ; return }; receiveLoad(.success(value), token: token) } catch { guard acceptingResponse() else { invalidate(); return }; receiveLoad(.failure(error), token: token) } }
  public func confirm(using operation: @escaping (NativeCampaignSectionsCommand) async throws -> NativeCampaignSectionsMutationResult, acceptingResponse: @escaping () -> Bool = { true }) async { guard let token = beginConfirmation(), let command = executing else { return }; do { let value = try await operation(command); guard acceptingResponse() else { invalidate(); return }; receiveMutation(.success(value), token: token) } catch { guard acceptingResponse() else { invalidate(); return }; receiveMutation(.failure(error), token: token) } }
  public func invalidate() { generation = UUID(); sections = nil; loading = false; mutationInFlight = false; pendingConfirmation = nil; executing = nil; errorMessage = nil; latestRevision = nil; gate.requireRefresh() }
  private func present(_ error: Error, mutation: Bool) {
    switch error as? NativeAPIError {
    case .some(.insufficientPermissions), .some(.reauthenticationRequired), .some(.workspaceAccessRemoved), .some(.notFound): invalidate()
    default: break
    }
    gate.requireRefresh(); switch error as? NativeAPIError { case .some(.conflict): errorMessage = "Campaign sections changed elsewhere. Refresh before making another explicit change; no retry was sent."; case .some(.insufficientPermissions): errorMessage = mutation ? "You no longer have permission to change campaign sections." : "You do not have permission to view these campaign sections."; case .some(.reauthenticationRequired): errorMessage = "Your session expired. Sign in again before loading or changing campaign sections."; case .some(.workspaceAccessRemoved): errorMessage = "Workspace access changed. Refresh your authorized workspace membership before continuing."; default: errorMessage = mutation ? "Could not confirm the change. Refresh before retrying; no change was queued." : "Campaign sections could not be loaded." } }
}

public struct NativeRichDocumentAnalysis: Equatable, Sendable {
  public enum Status: Equatable, Sendable { case supported(hasInertLinks: Bool), unsupported }
  public let status: Status
  public init(document: NativeJSONValue) { status = Self.analyze(document) }
  private static func analyze(_ value: NativeJSONValue) -> Status {
    guard case let .object(node) = value, case let .string(type)? = node["type"] else { return .unsupported }
    let children: [NativeJSONValue]
    if case let .array(value)? = node["content"] { children = value } else { children = [] }
    switch type {
    case "doc", "paragraph", "heading", "blockquote", "bulletList", "orderedList", "listItem":
      var hasLinks = false
      for child in children { guard case let .supported(childLinks) = analyze(child) else { return .unsupported }; hasLinks = hasLinks || childLinks }
      return .supported(hasInertLinks: hasLinks)
    case "hardBreak": return .supported(hasInertLinks: false)
    case "text":
      guard case .string? = node["text"] else { return .unsupported }
      guard case let .array(marks)? = node["marks"] else { return .supported(hasInertLinks: false) }
      var hasLink = false
      for mark in marks { guard case let .object(markObject) = mark, case let .string(markType)? = markObject["type"], ["bold", "italic", "link"].contains(markType) else { return .unsupported }; if markType == "link" { guard case let .object(attrs)? = markObject["attrs"], case .string? = attrs["href"] else { return .unsupported }; hasLink = true } }
      return .supported(hasInertLinks: hasLink)
    default: return .unsupported
    }
  }
}

struct NativeCampaignSectionsView: View {
  let campaignID: String; let campaignName: String; let workspace: Workspace; @ObservedObject var session: NativeSessionController; let api: any NativeAPIClient
  @StateObject private var coordinator: NativeCampaignSectionsCoordinator
  init(campaignID: String, campaignName: String, workspace: Workspace, session: NativeSessionController, api: any NativeAPIClient) { self.campaignID = campaignID; self.campaignName = campaignName; self.workspace = workspace; self.session = session; self.api = api; _coordinator = StateObject(wrappedValue: .init(capabilities: workspace.capabilities)) }
  var body: some View { List { header; if let sections = coordinator.sections { content(sections); audience(sections); channels(sections) } else if coordinator.loading { Section { ProgressView("Loading campaign sections…") } }; if let error = coordinator.errorMessage { Section { Label(error, systemImage: "exclamationmark.triangle").foregroundStyle(.orange); Button("Refresh") { Task { await load() } }.disabled(coordinator.loading || coordinator.mutationInFlight) } } }.navigationTitle("Campaign sections").refreshable { await load() }.task { await load() }.onChange(of: session.state) { _, _ in coordinator.invalidate() }.onDisappear { coordinator.invalidate() }.confirmationDialog("Confirm focused campaign change", isPresented: Binding(get: { coordinator.pendingConfirmation != nil }, set: { if !$0 { coordinator.cancelConfirmation() } })) { Button("Confirm change") { Task { await confirm() } }; Button("Cancel", role: .cancel) { coordinator.cancelConfirmation() } } message: { Text(confirmationText) } }
  @ViewBuilder private var header: some View { Section("Campaign") { Text(campaignName).font(.headline); if let revision = coordinator.latestRevision { Text("Revision \(revision) · source: canonical campaign sections").font(.caption).foregroundStyle(.secondary) }; Label(coordinator.gate.canMutate ? "Operator controls are limited to selection changes" : "Read-only until a canonical refresh succeeds", systemImage: "eye").font(.caption).foregroundStyle(.secondary); Text("No send, provider, channel, or delivery action is available here.").font(.caption).foregroundStyle(.secondary) } }
  @ViewBuilder private func content(_ sections: NativeCampaignSections) -> some View { Section("Content") { if let selection = sections.content.selection { Text("Selected: \(selection.template?.name ?? "Reviewed template unavailable")"); Text([selection.channel, selection.provider, selection.sourceVersion.map(String.init)].compactMap { $0 }.joined(separator: " · ")).font(.caption).foregroundStyle(.secondary) } else { Text("No reviewed template selected.").foregroundStyle(.secondary) }; ForEach(sections.content.templateOptions.items) { template in Button { coordinator.requestConfirmation(.selectTemplate(templateID: template.id, expectedRevision: sections.campaign.revision)) } label: { VStack(alignment: .leading) { Text(template.name); Text([template.subject, template.channel, template.reviewStatus, template.sourceVersion.map(String.init)].compactMap { $0 }.joined(separator: " · ")).font(.caption).foregroundStyle(.secondary) } }.disabled(!coordinator.gate.canMutate) }; if sections.content.templateOptions.truncated { Text("Partial list: more reviewed templates are available in the canonical workspace.").font(.caption).foregroundStyle(.orange) }; rich("Goal", sections.content.richContent.goalDocument); rich("Notes", sections.content.richContent.notesDocument); rich("Brief", sections.content.richContent.briefDocument) } }
  @ViewBuilder private func audience(_ sections: NativeCampaignSections) -> some View { Section("Audience") { if let selection = sections.audience.selection { Text(selection.name).font(.headline); audienceCounts(selection.counts); members("Included contacts", selection.includedContacts); members("Excluded contacts", selection.excludedContacts); members("Included stations", selection.includedStations); members("Excluded stations", selection.excludedStations); Button("Detach audience") { coordinator.requestConfirmation(.detachAudience(expectedRevision: sections.campaign.revision)) }.disabled(!coordinator.gate.canMutate) } else { Text("No audience selected.").foregroundStyle(.secondary) }; ForEach(sections.audience.options.items) { option in Button("Select \(option.name)") { coordinator.requestConfirmation(.attachAudience(audienceID: option.id, expectedRevision: sections.campaign.revision)) }.disabled(!coordinator.gate.canMutate) }; if sections.audience.options.truncated { Text("Partial list: more audiences are available in the canonical workspace.").font(.caption).foregroundStyle(.orange) } } }
  @ViewBuilder private func audienceCounts(_ counts: NativeCampaignSections.Counts) -> some View { if counts.available, let values = counts.values { Text("Contacts: \(values.includedContacts.map(String.init) ?? "unknown") included · \(values.excludedContacts.map(String.init) ?? "unknown") excluded").font(.caption).foregroundStyle(.secondary); Text("Stations: \(values.includedStations.map(String.init) ?? "unknown") included · \(values.excludedStations.map(String.init) ?? "unknown") excluded").font(.caption).foregroundStyle(.secondary) } else { Text("Exact audience totals unavailable: \(counts.reason ?? "not provided").").font(.caption).foregroundStyle(.orange) } }
  @ViewBuilder private func channels(_ sections: NativeCampaignSections) -> some View { Section("Channels") { Label(sections.channels.message ?? "Channels are unavailable.", systemImage: "exclamationmark.circle").foregroundStyle(.orange); Text("Reason: \(sections.channels.reason ?? "not provided")").font(.caption).foregroundStyle(.secondary) } }
  @ViewBuilder private func members(_ title: String, _ bounded: NativeCampaignSections.Bounded<NativeCampaignSections.Member>) -> some View { if !bounded.items.isEmpty { Text(title).font(.caption.bold()); ForEach(bounded.items) { Text($0.name ?? $0.id).font(.caption) } }; if bounded.truncated { Text("Partial \(title.lowercased()): additional members are not shown.").font(.caption2).foregroundStyle(.orange) } }
  @ViewBuilder private func rich(_ title: String, _ payload: NativeCampaignSections.RichDocument) -> some View { VStack(alignment: .leading, spacing: 6) { Text(title).font(.subheadline.bold()); if payload.available, let document = payload.document { NativeStructuredDocumentView(value: document) } else { Text("Structured content unavailable: \(payload.reason ?? "not provided").").font(.caption).foregroundStyle(.orange) } } }
  private var confirmationText: String { guard let pending = coordinator.pendingConfirmation else { return "" }; return "\(pending.command.consequence) Expected revision is captured from the loaded campaign. No send, provider, channel, or recipient delivery change will occur." }
  private func recoverAccess(_ error: Error, native: NativeSession) async {
    guard session.acceptsResponse(for: native, workspaceID: workspace.id) else { return }
    switch error as? NativeAPIError {
    case .some(.reauthenticationRequired): coordinator.invalidate(); try? session.sessionExpired()
    case .some(.workspaceAccessRemoved):
      coordinator.invalidate()
      await session.workspaceAccessRemoved(workspaceID: workspace.id, userID: native.userID, api: api)
    case .some(.notFound):
      session.removeCampaignSnapshot(campaignID: campaignID, workspaceID: workspace.id, requestSession: native)
    case .some(.insufficientPermissions):
      session.clearWorkspaceSnapshot(workspaceID: workspace.id, requestSession: native)
    default: break
    }
  }
  private func load() async { guard let native = session.sessionForRequests() else { return }; await coordinator.load(using: { do { return try await api.campaignSections(campaignID: campaignID, workspace: workspace, session: native) } catch { await recoverAccess(error, native: native); throw error } }, acceptingResponse: { session.acceptsResponse(for: native, workspaceID: workspace.id) }) }
  private func confirm() async { guard let native = session.sessionForRequests() else { return }; await coordinator.confirm(using: { command in do { return try await api.mutateCampaignSections(campaignID: campaignID, command: command, workspace: workspace, session: native) } catch { await recoverAccess(error, native: native); throw error } }, acceptingResponse: { session.acceptsResponse(for: native, workspaceID: workspace.id) }) }
}

private struct NativeStructuredDocumentView: View {
  let value: NativeJSONValue
  var body: some View { if case .unsupported = NativeRichDocumentAnalysis(document: value).status { Text("Unsupported structured content is unavailable on mobile.").font(.caption).foregroundStyle(.orange) } else { render(value) } }
  private func render(_ value: NativeJSONValue) -> AnyView { guard case let .object(object) = value, case let .string(type)? = object["type"] else { return AnyView(Text("Unsupported structured content is unavailable on mobile.").font(.caption).foregroundStyle(.orange)) }; let children: [NativeJSONValue] = { if case let .array(content)? = object["content"] { return content }; return [] }(); switch type { case "text": guard case let .string(text)? = object["text"] else { return AnyView(EmptyView()) }; return AnyView(markedText(text, marks: object["marks"])); case "hardBreak": return AnyView(Text("\n")); case "heading": return AnyView(VStack(alignment: .leading, spacing: 2) { ForEach(Array(children.enumerated()), id: \.offset) { _, child in render(child) } }.font(.headline)); case "blockquote": return AnyView(VStack(alignment: .leading, spacing: 4) { ForEach(Array(children.enumerated()), id: \.offset) { _, child in render(child) } }.padding(.leading, 8).overlay(alignment: .leading) { Rectangle().frame(width: 2).foregroundStyle(.secondary) }); case "bulletList", "orderedList": return AnyView(VStack(alignment: .leading, spacing: 4) { ForEach(Array(children.enumerated()), id: \.offset) { index, child in HStack(alignment: .top) { Text(type == "bulletList" ? "•" : "\(index + 1)."); render(child) } } }); case "listItem", "doc", "paragraph": return AnyView(VStack(alignment: .leading, spacing: 5) { ForEach(Array(children.enumerated()), id: \.offset) { _, child in render(child) } }); default: return AnyView(Text("Unsupported structured content is unavailable on mobile.").font(.caption).foregroundStyle(.orange)) } }
  private func markedText(_ string: String, marks: NativeJSONValue?) -> some View { var text = Text(string); guard case let .array(values)? = marks else { return AnyView(text.textSelection(.enabled)) }; var hasLink = false; for value in values { guard case let .object(mark) = value, case let .string(type)? = mark["type"] else { continue }; if type == "bold" { text = text.bold() }; if type == "italic" { text = text.italic() }; if type == "link" { hasLink = true; text = text.underline() } }; return AnyView(VStack(alignment: .leading, spacing: 2) { text.textSelection(.enabled); if hasLink { Text("Link preserved but unavailable on mobile.").font(.caption2).foregroundStyle(.orange) } }) }
}
